// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCja0ifInnTnRmGDxJgAeHdrznUfOsovXI',
    appId: '1:974680472249:web:3bb6fbb1312adfe8fab968',
    messagingSenderId: '974680472249',
    projectId: 'savetify',
    authDomain: 'savetify.firebaseapp.com',
    storageBucket: 'savetify.appspot.com',
    measurementId: 'G-LYX65TY1XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCt-oKCeSnIMslyRhq_PqEFyKbd8syWNg',
    appId: '1:974680472249:android:24b2b98c92b5cc4bfab968',
    messagingSenderId: '974680472249',
    projectId: 'savetify',
    storageBucket: 'savetify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNf2y8eLz4djnV5wdIxc_cdKVIqV7fQjY',
    appId: '1:974680472249:ios:547975e7fc97e157fab968',
    messagingSenderId: '974680472249',
    projectId: 'savetify',
    storageBucket: 'savetify.appspot.com',
    iosBundleId: 'com.example.savetify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNf2y8eLz4djnV5wdIxc_cdKVIqV7fQjY',
    appId: '1:974680472249:ios:547975e7fc97e157fab968',
    messagingSenderId: '974680472249',
    projectId: 'savetify',
    storageBucket: 'savetify.appspot.com',
    iosBundleId: 'com.example.savetify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCja0ifInnTnRmGDxJgAeHdrznUfOsovXI',
    appId: '1:974680472249:web:332684ed6c866114fab968',
    messagingSenderId: '974680472249',
    projectId: 'savetify',
    authDomain: 'savetify.firebaseapp.com',
    storageBucket: 'savetify.appspot.com',
    measurementId: 'G-69TFVCYR11',
  );
}
